config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#index'
  get 'blog', to: 'pages#blog'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    
  end
  
  def blog
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <h1 style="font-style:italic">Articles</h1>
    <%= link_to 'Home', root_path  %>
    
  </body>

</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title>Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <h1 style="font-style:italic">Welcome to the Home of ROR</h1>
      <%= link_to 'Blog', blog_path %>

  </body>

</html>